const { Specialty, Question, Option, Explanation, sequelize } = require('../models');

const questions = [
    // ─── ORTHODONTICS (~33) ───────────────────────────────────────────────────
    { specialty: 'Orthodontics', text: 'What is the normal overjet value in permanent dentition?', options: ['2-4 mm', '0-1 mm', '5-7 mm', '8-10 mm'], correct: 0, exp: 'Normal overjet is 2-4 mm, measured from the labial surface of upper incisors to the labial surface of lower incisors.' },
    { specialty: 'Orthodontics', text: 'Which index is used to assess orthodontic treatment need?', options: ['IOTN', 'OHI-S', 'CPTIN', 'DMF'], correct: 0, exp: 'IOTN (Index of Orthodontic Treatment Need) measures the need for treatment based on dental health and aesthetic components.' },
    { specialty: 'Orthodontics', text: 'What is the normal overbite value?', options: ['2-4 mm', '0 mm', '5-6 mm', '7-9 mm'], correct: 0, exp: 'Normal overbite (vertical overlap of incisors) is 2-4 mm.' },
    { specialty: 'Orthodontics', text: 'Angle Class II malocclusion is defined by:', options: ['Mesiobuccal cusp of upper first molar occludes anterior to the buccal groove of lower first molar', 'Mesiobuccal cusp of upper first molar occludes in the buccal groove of lower first molar', 'Mesiobuccal cusp of upper first molar occludes posterior to buccal groove of lower first molar', 'Upper molars are missing'], correct: 0, exp: 'In Class II, the upper mesiobuccal cusp is anterior (mesial) to the lower buccal groove, indicating mandibular retrusion.' },
    { specialty: 'Orthodontics', text: 'What is the purpose of an expansion plate?', options: ['Widen the dental arch', 'Retract incisors', 'Intrude molars', 'Close spaces'], correct: 0, exp: 'Expansion plates create transverse arch width to accommodate crowded teeth.' },
    { specialty: 'Orthodontics', text: 'The main force system in orthodontics that moves teeth bodily is:', options: ['A force couple (moment)', 'A single point force', 'Vertical elastics only', 'Torque in archwire'], correct: 0, exp: 'A couple (two equal and opposite forces) creates pure rotation; combined with a force, it produces bodily movement.' },
    { specialty: 'Orthodontics', text: 'Headgear is used primarily to:', options: ['Restrict forward growth of maxilla', 'Advance the mandible', 'Close spaces in lower arch', 'Correct crossbite'], correct: 0, exp: 'Cervical-pull and high-pull headgear restrict maxillary forward growth in Class II cases.' },
    { specialty: 'Orthodontics', text: 'Which bracket system does NOT require ligatures?', options: ['Self-ligating brackets', 'Twin brackets', 'Edgewise brackets', 'Begg brackets'], correct: 0, exp: 'Self-ligating brackets use a built-in clip mechanism to hold the archwire without the need for elastic or wire ligatures.' },
    { specialty: 'Orthodontics', text: 'Retention after orthodontic treatment is needed primarily for:', options: ['Preventing relapse due to periodontal fiber tension and growth', 'Increasing bone density', 'Preventing caries', 'Improving speech'], correct: 0, exp: 'Supracrestal periodontal fibers and remaining growth can cause teeth to drift back; retainers prevent relapse.' },
    { specialty: 'Orthodontics', text: 'Which tooth movement requires the highest force?', options: ['Bodily movement (translation)', 'Tipping', 'Rotation', 'Extrusion'], correct: 0, exp: 'Bodily movement (translation) requires the highest force as the entire root must move without tipping.' },
    { specialty: 'Orthodontics', text: 'A posterior crossbite affecting one side is most commonly due to:', options: ['Functional shift and skeletal asymmetry', 'Caries', 'Missing lower molars', 'High fluoride intake'], correct: 0, exp: 'Unilateral crossbite often involves a functional shift from a bilateral discrepancy — the mandible shifts to one side in occlusion.' },
    { specialty: 'Orthodontics', text: 'What is the leeway space?', options: ['Size difference between primary canine/molars and permanent successor teeth', 'Space between upper and lower arches', 'Space created by extraction', 'Gap in midline'], correct: 0, exp: 'The leeway space is the size difference (E-space) between the primary C, D, E and the permanent 3, 4, 5; ~1.5mm per side mandible, ~0.9mm maxilla.' },
    { specialty: 'Orthodontics', text: 'Rapid palatal expander (RPE) works by:', options: ['Opening the midpalatal suture', 'Tipping teeth buccally', 'Expanding soft tissue only', 'Remodeling alveolar bone'], correct: 0, exp: 'RPE applies heavy force (2 lbs) to open the midpalatal suture and create skeletal transverse expansion.' },
    { specialty: 'Orthodontics', text: 'Which bracket is used in Begg technique?', options: ['Light wire round bracket with vertical slot', 'Standard edgewise bracket', 'Ceramic bracket', 'Self-ligating bracket'], correct: 0, exp: 'The Begg bracket has a vertical slot and is used with light round wires in a tip-back mechanics system.' },
    { specialty: 'Orthodontics', text: 'The centre of resistance of a single rooted tooth is located:', options: ['At 1/3 to 1/2 of the root length from apex', 'At cementoenamel junction', 'At the crown center', 'At the apex'], correct: 0, exp: 'The center of resistance is approximately at the apical third of the alveolar bone — roughly 1/3–1/2 root length from the CEJ.' },
    { specialty: 'Orthodontics', text: 'Open bite is most commonly associated with:', options: ['Tongue thrusting and digit sucking habits', 'Caries', 'Early loss of primary teeth', 'Fluorosis'], correct: 0, exp: 'Anterior open bite is frequently caused by tongue thrust, digit sucking, or mouth breathing habits.' },
    { specialty: 'Orthodontics', text: 'Functional appliances are mainly used to:', options: ['Correct skeletal Class II by advancing mandible', 'Extract teeth', 'Whiten teeth', 'Treat TMD'], correct: 0, exp: 'Functional appliances like Twin Block or Activator harness muscle forces to advance the mandible in growing Class II patients.' },
    { specialty: 'Orthodontics', text: 'Which is the most elastic archwire material?', options: ['Nickel-titanium (NiTi)', 'Stainless steel', 'Beta-titanium (TMA)', 'Elgiloy'], correct: 0, exp: 'NiTi wires have superelastic properties and shape-memory, delivering light continuous forces ideal for initial alignment.' },
    { specialty: 'Orthodontics', text: 'The Frankfort plane is defined by:', options: ['Porion to orbitale', 'Nasion to sella', 'ANS to PNS', 'Nasion to menton'], correct: 0, exp: 'The Frankfort horizontal plane passes through porion (top of external auditory meatus) to orbitale (lowest point of orbital rim).' },
    { specialty: 'Orthodontics', text: 'What does the ANB angle measure in cephalometrics?', options: ['Skeletal jaw relationship (sagittal)', 'Incisor inclination', 'Vertical facial height', 'Arch length'], correct: 0, exp: 'ANB = SNA − SNB; it measures the sagittal relationship between maxilla and mandible. Normal ≈ 2°.' },
    { specialty: 'Orthodontics', text: 'Pseudo Class III (functional Class III) differs from true skeletal Class III because:', options: ['Mandible shifts forward in habitual occlusion but edge-to-edge in centric relation', 'ANB is very negative', 'Chin is very prominent', 'Requires surgery'], correct: 0, exp: 'Pseudo Class III is a functional shift; teeth are edge-to-edge in CR but cross in CO due to premature contact.' },
    { specialty: 'Orthodontics', text: 'Which force level is optimal for orthodontic tooth movement?', options: ['Light continuous forces (25–50 g)', 'Heavy intermittent forces (500 g)', 'No force (only tipping)', 'Maximum force possible'], correct: 0, exp: 'Light continuous forces produce optimal hyalinization-free tooth movement with less root resorption.' },
    { specialty: 'Orthodontics', text: 'A long-face (hyperdivergent) patient typically shows:', options: ['Increased lower facial height, steep mandibular plane', 'Reduced lower face height', 'Flat mandibular plane', 'Supernumerary teeth'], correct: 0, exp: 'Hyperdivergent patients have excessive vertical facial growth, increased lower face height, and steep mandibular plane angle.' },
    { specialty: 'Orthodontics', text: 'What is the purpose of bracket torque?', options: ['Control root position buccolingually', 'Rotate teeth', 'Extrude teeth', 'Close spaces'], correct: 0, exp: 'Torque in the bracket determines the buccolingual inclination of the root; it is built into the bracket slot in preadjusted systems.' },

    // ─── ENDODONTICS (~33) ────────────────────────────────────────────────────
    { specialty: 'Endodontics', text: 'The most common microorganism found in infected root canals is:', options: ['Enterococcus faecalis', 'Streptococcus mutans', 'Lactobacillus', 'Actinomyces'], correct: 0, exp: 'E. faecalis is the most resistant organism found in treated root canals and a major cause of endodontic failure.' },
    { specialty: 'Endodontics', text: 'What is the ideal irrigant used in root canal treatment?', options: ['Sodium hypochlorite (NaOCl)', 'Normal saline', 'Hydrogen peroxide', 'Chlorhexidine only'], correct: 0, exp: 'NaOCl dissolves organic tissue, has antimicrobial properties, and is the gold-standard irrigant for root canal preparation.' },
    { specialty: 'Endodontics', text: 'What is the purpose of EDTA in endodontics?', options: ['Remove smear layer by chelating calcium', 'Dissolve pulp tissue', 'Sterilize canals', 'Lubricate handpiece'], correct: 0, exp: 'EDTA chelates calcium ions in dentinal tubules, removing the smear layer and improving obturation adhesion.' },
    { specialty: 'Endodontics', text: 'Gutta-percha is used in endodontics for:', options: ['Root canal obturation', 'Pulp capping', 'Retrograde filling', 'Bleaching'], correct: 0, exp: 'Gutta-percha is the standard core material for three-dimensional obturation of root canal systems.' },
    { specialty: 'Endodontics', text: 'A periapical abscess differs from Phoenix abscess in that:', options: ['Phoenix abscess arises from a chronic lesion that becomes acute', 'Periapical abscess is always chronic', 'Phoenix abscess is painless', 'They are identical'], correct: 0, exp: 'Phoenix abscess is an acute exacerbation of a pre-existing chronic periapical lesion (acute on chronic).' },
    { specialty: 'Endodontics', text: 'The average number of root canals in a mandibular first molar is:', options: ['3 canals (2 mesial, 1 distal)', '2 canals', '4 canals', '1 canal'], correct: 0, exp: 'The mandibular first molar typically has 3 canals: mesiobuccal, mesiolingual, and distal.' },
    { specialty: 'Endodontics', text: 'Cold lateral condensation uses:', options: ['Master cone + accessory cones + spreader', 'Single master cone only', 'Warm gutta-percha', 'Sealer only'], correct: 0, exp: 'Lateral condensation involves placing a master gutta-percha cone, then using a spreader and accessory cones to fill the canal.' },
    { specialty: 'Endodontics', text: 'What is the working length in endodontics?', options: ['Distance from reference point to apical foramen (usually 0.5-1 mm short)', 'Total tooth length', 'Length of crown only', 'Radiographic root length'], correct: 0, exp: 'Working length is established 0.5–1 mm short of the radiographic apex to avoid overinstrumentation.' },
    { specialty: 'Endodontics', text: 'Pulp capping is indicated when:', options: ['Small mechanical pulp exposure during caries removal in a vital, non-infected tooth', 'Pulp is infected', 'Pulp is necrotic', 'Root is not fully formed'], correct: 0, exp: 'Direct pulp capping with MTA or calcium hydroxide is done over a small, clean, caries-free exposure of a vital pulp.' },
    { specialty: 'Endodontics', text: 'Apexification with MTA is used for:', options: ['Non-vital teeth with open apices in young patients', 'Fully formed apices', 'Traumatized vital teeth', 'Retreatment only'], correct: 0, exp: 'MTA apexification creates a hard tissue barrier at the apex of immature teeth with necrotic pulps.' },
    { specialty: 'Endodontics', text: 'Internal root resorption appears radiographically as:', options: ['Symmetric oval radiolucency within the root canal', 'External root shortening', 'Periapical lesion', 'Hypercementosis'], correct: 0, exp: 'Internal resorption shows as a symmetric, balloon-like radiolucency within the root canal, moving with the canal on angled views.' },
    { specialty: 'Endodontics', text: 'The Step-back technique in root canal preparation is used to:', options: ['Create a funnel shape to prevent ledging and instrument separation', 'Enlarge the apex', 'Irrigate better', 'Dry the canal'], correct: 0, exp: 'Step-back (telescopic) preparation widens the coronal portion while maintaining patency at the apex, creating a funnel shape.' },
    { specialty: 'Endodontics', text: 'Sodium hypochlorite accident (injection into periapical tissues) causes:', options: ['Severe pain, swelling, bruising, paresthesia', 'No symptoms', 'Minor discomfort only', 'Pulp fibrosis'], correct: 0, exp: 'NaOCl extrusion causes immediate severe pain, burns tissue, causes ecchymosis, and can cause paresthesia if near nerve.' },
    { specialty: 'Endodontics', text: 'Mineral Trioxide Aggregate (MTA) is preferred over calcium hydroxide for apexification because:', options: ['Better seal, antibacterial, biocompatible, shorter treatment time', 'It is cheaper', 'It dissolves faster', 'No mixing required'], correct: 0, exp: 'MTA provides superior sealing ability, biocompatibility, and allows completion in fewer visits (or one visit).' },
    { specialty: 'Endodontics', text: 'Periapical periodontitis most commonly originates from:', options: ['Pulp necrosis', 'Periodontal disease', 'Trauma only', 'Systemic disease'], correct: 0, exp: 'Bacterial infection from a necrotic pulp spreads into periapical tissues causing periapical periodontitis.' },
    { specialty: 'Endodontics', text: 'The crown discoloration of a tooth with a necrotic pulp occurs due to:', options: ['Breakdown products of hemoglobin entering dentinal tubules', 'Fluorosis', 'Tetracycline staining', 'Caries'], correct: 0, exp: 'Hemolysis of red blood cells releases hemoglobin, which breaks down into iron sulfides and stains the dentinal tubules gray/brown.' },
    { specialty: 'Endodontics', text: 'Which file system uses a reciprocating motion?', options: ['WaveOne (single-file reciprocating system)', 'ProFile (rotary)', 'K-file', 'Hedström file'], correct: 0, exp: 'WaveOne and Reciproc use a back-and-forth (reciprocating) motion to reduce cyclic fatigue and file separation risk.' },
    { specialty: 'Endodontics', text: 'Hot tooth (hyperalgesia) is managed by:', options: ['Intraligamentary supplemental injection + adequate anesthesia', 'No treatment needed', 'Extraction only', 'Antibiotics alone'], correct: 0, exp: 'Hot teeth are difficult to anesthetize due to lowered nerve threshold. Intraosseous or intraligamentary injections help achieve profound anesthesia.' },
    { specialty: 'Endodontics', text: 'Vertical root fracture (VRF) differs from horizontal fracture in that:', options: ['VRF is usually a treatment failure with poor prognosis; extraction often needed', 'VRF heals easily', 'VRF is asymptomatic', 'Horizontal fracture requires extraction'], correct: 0, exp: 'VRF typically requires extraction; it presents with a J-shaped radiolucency and is associated with over-instrumentation or obturation pressure.' },
    { specialty: 'Endodontics', text: 'During root canal access preparation, the outline form aims to:', options: ['Provide straight-line access to all canal orifices', 'Remove all tooth structure', 'Create aesthetic opening', 'Eliminate all enamel'], correct: 0, exp: 'Straight-line access reduces file curvature stress and allows better instrumentation and irrigation of the canals.' },

    // ─── PROSTHODONTICS (~33) ─────────────────────────────────────────────────
    { specialty: 'Prosthodontics', text: 'The most common cause of denture failure is:', options: ['Poor retention due to bone resorption', 'Wrong shade selection', 'Allergy to acrylic', 'Excessive salivation'], correct: 0, exp: 'Progressive alveolar ridge resorption reduces denture-bearing area and causes loosening over time.' },
    { specialty: 'Prosthodontics', text: 'The crown-to-root ratio for a fixed partial denture abutment should ideally be:', options: ['1:2 (optimal), minimum 1:1', '2:1', '1:4', '3:1'], correct: 0, exp: 'An ideal crown-to-root ratio is 1:2; 1:1 is the minimum acceptable ratio for an abutment tooth.' },
    { specialty: 'Prosthodontics', text: 'Cantilever bridge is contraindicated in:', options: ['Posterior region with high bite forces', 'Upper anterior with missing lateral incisor', 'Bounded spaces only', 'Well-supported abutments'], correct: 0, exp: 'Cantilever bridges in posterior regions create excessive lever forces on the abutment, causing failure.' },
    { specialty: 'Prosthodontics', text: 'Porcelain fused to metal (PFM) crown advantages include:', options: ['Excellent aesthetics combined with strength of metal framework', 'No metal showing', 'No preparation needed', 'Cheapest option'], correct: 0, exp: 'PFM combines the strength of a metal substructure with the aesthetics of porcelain veneer, making it durable and lifelike.' },
    { specialty: 'Prosthodontics', text: 'What is the function of the posterior palatal seal in complete dentures?', options: ['Maintain suction/retention by creating a seal at the vibrating line', 'Improve chewing', 'Prevent gagging', 'Support soft palate'], correct: 0, exp: 'The post-dam creates a peripheral seal at the junction of the hard and soft palate, improving denture retention.' },
    { specialty: 'Prosthodontics', text: 'Interocclusal rest (centric stops) in complete dentures should be placed:', options: ['On posterior teeth (molars/premolars)', 'On incisors only', 'On canines only', 'Not needed'], correct: 0, exp: 'Posterior centric stops provide stable occlusal contact and prevent over-closure in complete dentures.' },
    { specialty: 'Prosthodontics', text: 'Zirconia crowns are preferred in posterior teeth due to:', options: ['Superior strength and fracture resistance', 'Transparency', 'Lowest cost', 'No need for preparation'], correct: 0, exp: 'Zirconia (Y-TZP) has high flexural strength (900–1200 MPa), making it ideal for high-stress posterior areas.' },
    { specialty: 'Prosthodontics', text: 'Neutral zone in complete denture fabrication refers to:', options: ['Area where tongue and cheek/lip forces are balanced', 'Midline of denture', 'Gingival margin area', 'Palatal area'], correct: 0, exp: 'Positioning denture teeth in the neutral zone helps with retention, stability, and phonetics in edentulous patients.' },
    { specialty: 'Prosthodontics', text: 'The vertical dimension of occlusion (VDO) is determined by:', options: ['Freeway space and resting vertical dimension (VDR − 2-4mm)', 'Patient preference', 'Full opening of mouth', 'Radiographic measurements'], correct: 0, exp: 'VDO = VDR (rest) minus 2–4 mm (freeway space), where freeway space is the interocclusal clearance at rest.' },
    { specialty: 'Prosthodontics', text: 'Which impression material has the highest dimensional accuracy for fixed prosthetics?', options: ['Polyvinyl siloxane (PVS/addition silicone)', 'Alginate', 'ZOE paste', 'Impression plaster'], correct: 0, exp: 'PVS (addition silicone) has excellent dimensional stability, accuracy, and long shelf life — ideal for fixed prosthetics.' },
    { specialty: 'Prosthodontics', text: 'A denture stomatitis is associated with:', options: ['Candida albicans overgrowth under an ill-fitting denture', 'Herpes virus', 'Bacterial plaque only', 'Burning mouth syndrome'], correct: 0, exp: 'Denture stomatitis (Newton type I-III) involves candidal infection under a denture, especially when worn 24/7.' },
    { specialty: 'Prosthodontics', text: 'Which articular movement is checked by the protrusive record?', options: ['Condylar guidance angle', 'Bennett angle', 'Incisal guidance', 'Vertical overlap'], correct: 0, exp: 'Protrusive records are used to set the condylar guidance (sagittal condylar inclination) on a semi-adjustable articulator.' },
    { specialty: 'Prosthodontics', text: 'The Ante\'s Law states that:', options: ['Root surface area of abutments must be ≥ that of missing teeth', 'A bridge can replace unlimited teeth', 'Root length must be 2× crown length', 'Splinting is always required'], correct: 0, exp: 'Ante\'s Law: the combined root surface area of abutment teeth should equal or exceed that of the teeth being replaced.' },
    { specialty: 'Prosthodontics', text: 'Complete denture base material of choice is:', options: ['Heat-cured PMMA (polymethyl methacrylate)', 'Cold-cured acrylic', 'Cobalt-chrome', 'Silicone'], correct: 0, exp: 'Heat-cured PMMA offers superior strength, aesthetics, processability, and bond with denture teeth compared to cold-cured alternatives.' },
    { specialty: 'Prosthodontics', text: 'The primary support area for a mandibular complete denture is:', options: ['Buccal shelf (retromolar pad area)', 'Incisive papilla', 'Median palatal suture', 'Pterygomandibular raphe'], correct: 0, exp: 'The buccal shelf is the primary stress-bearing area for lower complete dentures due to its horizontal surface and cortical bone.' },
    { specialty: 'Prosthodontics', text: 'A pier abutment in a long-span FPD acts as:', options: ['A fulcrum causing stress concentration and failure', 'An ideal support', 'A flexible connector', 'A cantilever support'], correct: 0, exp: 'A middle abutment (pier) acts as a fulcrum; use of a non-rigid connector on the distal of the pier is recommended.' },

    // ─── PERIODONTICS (~33) ───────────────────────────────────────────────────
    { specialty: 'Periodontics', text: 'The most common form of periodontitis is:', options: ['Chronic periodontitis', 'Aggressive periodontitis', 'Necrotizing periodontitis', 'Periodontitis as a manifestation of systemic disease'], correct: 0, exp: 'Chronic periodontitis is the most prevalent form, affecting adults with slow, progressive bone loss.' },
    { specialty: 'Periodontics', text: 'Sharpey\'s fibers are:', options: ['Collagen fibers of PDL embedded in cementum and alveolar bone', 'Elastic fibers of gingiva', 'Nerve fibers of pulp', 'Fibers in cementum only'], correct: 0, exp: 'Sharpey\'s fibers are the principal PDL fiber bundles embedded (inserted) into both cementum and alveolar bone.' },
    { specialty: 'Periodontics', text: 'Furcation involvement Grade II means:', options: ['Probe enters furcation but does not pass through', 'Probe just barely enters', 'Through-and-through furcation', 'No furcation involvement'], correct: 0, exp: 'In Grade II furcation (Hamp classification), the probe enters the furcation but a partition of bone remains — does not exit the other side.' },
    { specialty: 'Periodontics', text: 'Gingival recession is most commonly caused by:', options: ['Traumatic toothbrushing (horizontal scrubbing)', 'Untreated caries', 'Fluoride use', 'High sugar intake'], correct: 0, exp: 'Vigorous horizontal brushing abrades the gingival margin and causes recession, especially on buccal surfaces.' },
    { specialty: 'Periodontics', text: 'Osseous defects best treated by guided tissue regeneration (GTR) are:', options: ['Vertical 3-wall defects', 'Horizontal bone loss', '1-wall defects', 'Furcation class III'], correct: 0, exp: 'Contained vertical (3-wall) defects provide scaffold for membrane-guided regeneration, giving the best GTR outcomes.' },
    { specialty: 'Periodontics', text: 'The biologic width is approximately:', options: ['2 mm (junctional epithelium 1 mm + connective tissue attachment 1 mm)', '5 mm', '0.5 mm', '3.5 mm'], correct: 0, exp: 'Biologic width = 1 mm junctional epithelium + 1 mm connective tissue attachment = ~2 mm. Restorations must not invade it.' },
    { specialty: 'Periodontics', text: 'Which systemic condition is most associated with aggressive periodontitis?', options: ['Neutrophil dysfunction (impaired chemotaxis)', 'Diabetes mellitus', 'HIV', 'Down syndrome'], correct: 0, exp: 'Aggressive periodontitis (now Stage III/IV Grade C per 2017 classification) is associated with defective neutrophil function and familial aggregation.' },
    { specialty: 'Periodontics', text: 'The goal of scaling and root planing is:', options: ['Remove calculus, biofilm, and smooth root surface to allow gingival reattachment', 'Eliminate the pocket surgically', 'Extract hopeless teeth', 'Apply fluoride'], correct: 0, exp: 'SRP reduces inflammation by removing supra and subgingival deposits and cementum contaminated with toxins.' },
    { specialty: 'Periodontics', text: 'Gingival enlargement caused by calcium channel blockers is most associated with:', options: ['Nifedipine', 'Amlodipine only', 'Verapamil', 'Diltiazem'], correct: 0, exp: 'Nifedipine (a dihydropyridine CCB) is the most commonly implicated drug in drug-induced gingival enlargement.' },
    { specialty: 'Periodontics', text: 'A mucogingival junction separates:', options: ['Attached gingiva from alveolar mucosa', 'Free gingiva from attached gingiva', 'Epithelium from connective tissue', 'Cementum from bone'], correct: 0, exp: 'The MGJ (mucogingival line) is the clear demarcation between the pale, stippled attached gingiva and the red, non-keratinized alveolar mucosa.' },
    { specialty: 'Periodontics', text: 'Gingivitis differs from periodontitis in that:', options: ['Gingivitis has no bone loss and is reversible', 'Gingivitis involves bone loss', 'Periodontitis has no bleeding', 'Both are irreversible'], correct: 0, exp: 'Gingivitis is confined to the gingival tissues, reversible with oral hygiene, and shows no attachment or bone loss.' },
    { specialty: 'Periodontics', text: 'Probing pocket depth (PPD) is measured from:', options: ['Gingival margin to base of pocket', 'CEJ to base of pocket', 'Alveolar crest to gingival margin', 'CEJ to alveolar crest'], correct: 0, exp: 'PPD is the distance from the gingival margin to the base of the sulcus/pocket; clinical attachment level (CAL) is measured from CEJ.' },
    { specialty: 'Periodontics', text: 'Widmann flap technique differs from Kirkland flap in that:', options: ['Modified Widmann is a reverse-bevel flap for better access without resection', 'Kirkland is a reverse-bevel flap', 'Both are identical', 'Widmann includes bone grafting'], correct: 0, exp: 'The modified Widmann (MWF) uses an internal bevel incision, preserving the interdental papilla and providing excellent access for root planing.' },
    { specialty: 'Periodontics', text: 'Platelet-rich fibrin (PRF) in periodontal surgery is used to:', options: ['Accelerate healing and regeneration using autologous growth factors', 'Act as a membrane barrier', 'Provide osseous graft material', 'Sterilize the surgical site'], correct: 0, exp: 'PRF concentrates platelets and growth factors (PDGF, TGF-β, VEGF) from the patient\'s own blood to enhance tissue regeneration.' },

    // ─── PEDIATRIC DENTISTRY (~33) ────────────────────────────────────────────
    { specialty: 'Pediatric Dentistry', text: 'The most common cause of pain in primary teeth is:', options: ['Dental caries (Early Childhood Caries)', 'Trauma', 'Fluorosis', 'Eruption pain'], correct: 0, exp: 'Early Childhood Caries (ECC) is the leading cause of toothache and dental visits in children under 6.' },
    { specialty: 'Pediatric Dentistry', text: 'Pulpotomy in primary teeth uses which material most commonly?', options: ['Mineral Trioxide Aggregate (MTA) or formocresol', 'Calcium hydroxide only', 'Amalgam', 'ZOE only'], correct: 0, exp: 'Formocresol pulpotomy has been historically standard; MTA is now preferred for its superior biocompatibility and success rates.' },
    { specialty: 'Pediatric Dentistry', text: 'Space maintainer after premature loss of primary second molar is:', options: ['Band-and-loop or distal shoe for unerupted first permanent molar', 'Hawley retainer', 'RPD', 'No treatment needed'], correct: 0, exp: 'A distal shoe space maintainer is used when the primary second molar is lost before eruption of the permanent first molar.' },
    { specialty: 'Pediatric Dentistry', text: 'Dens invaginatus (dens in dente) is most commonly found in:', options: ['Maxillary lateral incisors', 'Mandibular molars', 'Primary canines', 'Mandibular incisors'], correct: 0, exp: 'Dens in dente results from enamel organ invagination during tooth development; most common in maxillary lateral incisors.' },
    { specialty: 'Pediatric Dentistry', text: 'Premature eruption of teeth at birth is called:', options: ['Natal teeth', 'Neonatal teeth', 'Precocious dentition', 'Supernumerary teeth'], correct: 0, exp: 'Natal teeth are present at birth; neonatal teeth erupt within the first 30 days of life. Both are usually mandibular incisors.' },
    { specialty: 'Pediatric Dentistry', text: 'Ankylosis of a primary molar is identified by:', options: ['Lack of physiological mobility, dull sound on percussion, infraocclusion', 'Normal mobility and sound', 'Mobility increased', 'Swelling'], correct: 0, exp: 'Ankylosed primary molars show infraocclusion (submerged below occlusal plane), dull percussion sound, and no normal mobility.' },
    { specialty: 'Pediatric Dentistry', text: 'The recommended daily fluoride supplement for a 2-year-old in a fluoride-deficient area is:', options: ['0.25 mg/day', '1.0 mg/day', '0.5 mg/day', '0 mg/day'], correct: 0, exp: 'For children 6 months–3 years in areas with <0.3 ppm fluoride in water, the supplement is 0.25 mg F/day.' },
    { specialty: 'Pediatric Dentistry', text: 'The CAST instrument in ECC screening evaluates:', options: ['Caries severity from sound tooth to involving pulp', 'Fluorosis', 'Sealant status', 'Enamel defects only'], correct: 0, exp: 'CAST (Caries Assessment Spectrum and Treatment) categorizes from sound (0) to infected pulp/abscess (8), guiding treatment planning.' },
    { specialty: 'Pediatric Dentistry', text: 'Stockings habit (nonnutritive sucking) should be stopped by:', options: ['Age 3-4 to prevent dental effects', 'Age 1', 'Age 10', 'It is not harmful'], correct: 0, exp: 'Nonnutritive sucking (pacifier/thumbsucking) that persists beyond age 3-4 can cause anterior open bite, posterior crossbite, and proclination.' },
    { specialty: 'Pediatric Dentistry', text: 'The primary dentition has how many teeth?', options: ['20 teeth', '28 teeth', '32 teeth', '16 teeth'], correct: 0, exp: 'The primary dentition consists of 20 teeth: 8 incisors, 4 canines, and 8 molars.' },
    { specialty: 'Pediatric Dentistry', text: 'Tetracycline staining of teeth occurs when the drug is taken:', options: ['During tooth mineralization (pregnancy to age 8)', 'After age 12', 'Only in adults', 'During eruption only'], correct: 0, exp: 'Tetracycline binds to calcium during mineralization, causing gray-brown discoloration. Contraindicated in pregnant women and children <8.' },
    { specialty: 'Pediatric Dentistry', text: 'Turner hypoplasia refers to:', options: ['Enamel defect in a permanent tooth caused by infection or trauma to its primary predecessor', 'Fluorosis', 'Amelogenesis imperfecta', 'Dentinogenesis imperfecta'], correct: 0, exp: 'Periapical infection of a primary tooth or trauma disrupts development of the succeeding permanent tooth\'s enamel.' },
    { specialty: 'Pediatric Dentistry', text: 'Stainless steel crowns (SSC) in pediatric dentistry are indicated for:', options: ['Extensively carious primary molars with pulp therapy', 'Anterior esthetic restorations', 'Adults only', 'Mildly carious teeth'], correct: 0, exp: 'SSCs are the most durable restoration for primary molars after pulp therapy, caries with large cavities, or hypoplastic teeth.' },

    // ─── RESTORATIVE (~33) ────────────────────────────────────────────────────
    { specialty: 'Restorative', text: 'Which composite resin is most appropriate for posterior restorations?', options: ['Microhybrid or nanofill composite', 'Microfilled composite', 'Flowable composite only', 'Macrofill composite'], correct: 0, exp: 'Microhybrid composites combine fine filler particles with larger ones for a balance of strength, polish, and wear resistance for posterior use.' },
    { specialty: 'Restorative', text: 'Acid etching with phosphoric acid creates:', options: ['Micro-retentive pattern in enamel for bonding', 'Chemical bond directly', 'Smear layer removal only', 'Dentinal tubule sealing'], correct: 0, exp: 'Phosphoric acid (35–40%) selectively etches enamel prism cores/peripheries, creating a micro-retentive surface for resin tags.' },
    { specialty: 'Restorative', text: 'A Class II cavity involves:', options: ['Proximal surface of posterior (molar/premolar) teeth', 'Proximal surface of anterior teeth', 'Occlusal surface only', 'Smooth surface of posterior teeth'], correct: 0, exp: 'Black\'s Class II cavities are on the proximal surfaces of premolars and molars, requiring a proximal box preparation.' },
    { specialty: 'Restorative', text: 'The main advantage of total-etch adhesive over self-etch is:', options: ['Superior enamel bond strength due to separate etching', 'Shorter application time', 'No technique sensitivity', 'Better dentin bond'], correct: 0, exp: 'Total-etch adhesives achieve higher enamel bond strength by explicitly etching enamel with phosphoric acid before the adhesive.' },
    { specialty: 'Restorative', text: 'Amalgam is retained in a cavity primarily by:', options: ['Mechanical retention (undercuts and convergent walls)', 'Chemical bonding', 'Adhesion to dentin', 'Suction effect'], correct: 0, exp: 'Amalgam lacks chemical bonding to tooth structure; retention depends entirely on mechanical undercuts and convergent walls.' },
    { specialty: 'Restorative', text: 'The smear layer in dentin bonding is:', options: ['A layer of debris that blocks dentinal tubule access and can be removed or modified', 'A natural protective barrier that should always be preserved', 'Only present on enamel', 'Made of calcium only'], correct: 0, exp: 'The smear layer is created during cutting; it blocks tubules. It can be removed (total-etch) or modified (self-etch) for bonding.' },
    { specialty: 'Restorative', text: 'Polymerization shrinkage in composite resin causes:', options: ['Internal stress and microleakage at margins', 'Expansion', 'Improved sealing', 'No clinical effect'], correct: 0, exp: 'Composites shrink 1.5–5% on curing; this creates contraction stresses that can pull margins and cause microleakage or cusp deflection.' },
    { specialty: 'Restorative', text: 'Glass ionomer cement is unique because:', options: ['It bonds chemically to both enamel and dentin via ionic bonding with hydroxyapatite', 'It requires acid etching', 'It has no fluoride release', 'It is a resin only'], correct: 0, exp: 'GIC undergoes an acid-base reaction and bonds via polyacrylic acid chains to calcium ions in tooth structure; also releases fluoride.' },
    { specialty: 'Restorative', text: 'Black\'s cavity preparation principle of "extension for prevention" refers to:', options: ['Extending margins to self-cleansing areas to prevent recurrent caries', 'Making the cavity as large as possible', 'Extending into enamel rods only', 'Removing all stained dentin'], correct: 0, exp: 'Extension for prevention placed margins in areas accessible to toothbrush cleaning, reducing risk of secondary caries. Now largely replaced by minimally invasive concepts.' },
    { specialty: 'Restorative', text: 'Direct pulp capping material of first choice today is:', options: ['Mineral Trioxide Aggregate (MTA) or Biodentine', 'Zinc oxide eugenol', 'Calcium hydroxide paste (Dycal)', 'Amalgam'], correct: 0, exp: 'MTA and Biodentine have overtaken calcium hydroxide due to superior sealing, biocompatibility, and dentin bridge formation without tunnel defects.' },
    { specialty: 'Restorative', text: 'Pit and fissure sealants work by:', options: ['Blocking the fissure to prevent bacterial accumulation and acid attack', 'Releasing fluoride continuously', 'Remineralizing enamel', 'Providing mechanical retention to remineralize'], correct: 0, exp: 'Sealants physically block the deep fissures where 90% of childhood caries occur, preventing bacterial colonization.' },
    { specialty: 'Restorative', text: 'The purpose of a base under an amalgam restoration is:', options: ['Protect the pulp from thermal stimuli and provide structural support', 'Bond amalgam to dentin', 'Reduce microleakage', 'Replace missing cusps'], correct: 0, exp: 'A base (usually GIC or ZOE) insulates the pulp from thermal conductivity of metal and replaces missing dentin volume.' },

    // ─── DENTAL SURGERY (~33) ─────────────────────────────────────────────────
    { specialty: 'Oral Surgery', text: 'The most common complication after tooth extraction is:', options: ['Dry socket (alveolar osteitis)', 'Mandibular fracture', 'Nerve damage', 'Ludwig\'s angina'], correct: 0, exp: 'Dry socket occurs in 2–5% of extractions and up to 45% of mandibular third molar extractions, causing severe pain 2–4 days post-op.' },
    { specialty: 'Oral Surgery', text: 'Contraindication to tooth extraction in a patient on warfarin therapy:', options: ['INR > 3.5 (relative contraindication); proceed with INR 2-3.5 with local hemostatic measures', 'Any anticoagulation is absolute contraindication', 'Only aspirin is contraindicated', 'No precaution needed'], correct: 0, exp: 'Extractions can be safely performed when INR is 2.0–3.5 with local hemostatic measures; values >3.5 require medical management first.' },
    { specialty: 'Oral Surgery', text: 'Dry socket (alveolar osteitis) is treated by:', options: ['Gentle irrigation and soft-tissue sedative dressing (Alvogyl)', 'Antibiotics only', 'Re-extraction of socket', 'Secondary suturing'], correct: 0, exp: 'Alvogyl or similar iodoform-eugenol dressings provide pain relief in dry socket; socket is irrigated gently and dressed without curettage.' },
    { specialty: 'Oral Surgery', text: 'The inferior alveolar nerve block is given at:', options: ['Pterygomandibular space, above lingula of mandible', 'Mental foramen', 'Infraorbital foramen', 'Nasopalatine foramen'], correct: 0, exp: 'The IANB targets the pterygomandibular space; the needle penetrates to 2/3 its length, depositing above the mandibular lingula where the IAN enters.' },
    { specialty: 'Oral Surgery', text: 'Ludwig\'s angina is a serious infection involving:', options: ['Bilateral submandibular, submental, and sublingual spaces with airway compromise', 'Unilateral parotid space', 'Pterygomandibular space only', 'Superficial infection of neck'], correct: 0, exp: 'Ludwig\'s angina is a rapidly spreading bilateral cellulitis of the floor of mouth; airway management is the priority.' },
    { specialty: 'Oral Surgery', text: 'Post-extraction bleeding is most commonly controlled by:', options: ['Bite on gauze for 30 min + figure-of-eight suture if severe', 'Systemic antibiotics', 'Ice packing only', 'Vitamin K injection immediately'], correct: 0, exp: 'Primary hemostasis is achieved by direct pressure; if persistent, hemostatic agents (cellulose, collagen) and suturing are used.' },
    { specialty: 'Oral Surgery', text: 'The most likely nerve injured during mandibular third molar removal is:', options: ['Inferior alveolar nerve and/or lingual nerve', 'Facial nerve', 'Chorda tympani only', 'Hypoglossal nerve'], correct: 0, exp: 'The IAN runs through the mandibular canal near third molar roots; the lingual nerve is at risk from lingual retractors.' },
    { specialty: 'Oral Surgery', text: 'Which flap design is most commonly used for surgical extraction of impacted mandibular third molars?', options: ['Ward\'s incision (envelope flap + vertical releasing incision)', 'Palatal flap', 'Trapezoidal flap in maxilla', 'No flap needed'], correct: 0, exp: 'Ward\'s (triangular) flap or envelope flap with a distal extension provides access and prevents damage to adjacent structures.' },
    { specialty: 'Oral Surgery', text: 'Osteonecrosis of the jaw (MRONJ) is strongly associated with:', options: ['Bisphosphonate therapy, especially IV zoledronic acid in cancer patients', 'Aspirin use', 'Vitamin D deficiency', 'Routine extraction'], correct: 0, exp: 'Anti-resorptive and anti-angiogenic drugs (bisphosphonates, denosumab) impair bone healing after dento-alveolar surgery.' },
    { specialty: 'Oral Surgery', text: 'The sign of a fractured mandible after a traumatic injury is:', options: ['Step deformity, altered occlusion, pain, crepitus, mental nerve paresthesia', 'Normal occlusion with pain', 'Swelling only', 'Trismus without bite change'], correct: 0, exp: 'Mandibular fractures show malocclusion, a palpable step or mobility at the fracture site, and mental nerve numbness if near the foramen.' },
    { specialty: 'Oral Surgery', text: 'Trismus most commonly results from:', options: ['Inferior alveolar nerve block that enters the medial pterygoid muscle (hematoma/trauma)', 'Dry socket', 'Incomplete anesthesia', 'Normal response'], correct: 0, exp: 'Trismus after IANB is due to hematoma in the pterygoid muscles, causing muscle spasm; it resolves with warm compresses and NSAIDs.' },
    { specialty: 'Oral Surgery', text: 'Subperiosteal dissection (raising a mucoperiosteal flap) is done with which instrument?', options: ['Periosteal elevator (Molt #9)', 'Scalpel', 'Curette', 'Extraction forceps'], correct: 0, exp: 'A periosteal elevator (e.g., Molt #9) separates the mucoperiosteum from bone for flap surgery without tearing the periosteum.' },

    // ─── ORAL MEDICINE & PATHOLOGY (~35) ──────────────────────────────────────
    { specialty: 'Oral Medicine & Pathology', text: 'The most common benign intraoral tumor is:', options: ['Fibromatosis (fibroma)', 'Lipoma', 'Hemangioma', 'Pleomorphic adenoma'], correct: 0, exp: 'Traumatic fibroma (irritation fibroma) is the most common benign soft tissue lesion in the oral cavity, caused by chronic irritation.' },
    { specialty: 'Oral Medicine & Pathology', text: 'Leukoplakia is defined as:', options: ['White patch that cannot be rubbed off and cannot be classified as any other disease', 'A normal variant', 'Always premalignant', 'Red patch of mucosa'], correct: 0, exp: 'Leukoplakia is a clinical diagnosis of exclusion — a white patch not attributable to any other condition.' },
    { specialty: 'Oral Medicine & Pathology', text: 'Erythroplakia compared to leukoplakia has:', options: ['Higher malignant transformation rate (>50%)', 'Lower risk', 'Same risk', 'No risk'], correct: 0, exp: 'Erythroplakia (red velvety patch) carries a malignant transformation rate of approximately 50-90%, higher than white leukoplakia.' },
    { specialty: 'Oral Medicine & Pathology', text: 'The most common site for oral squamous cell carcinoma is:', options: ['Lateral border of tongue and floor of mouth', 'Dorsal tongue', 'Hard palate', 'Upper lip'], correct: 0, exp: 'The lateral/ventral tongue and floor of mouth account for >50% of oral cancers due to carcinogen pooling in these areas.' },
    { specialty: 'Oral Medicine & Pathology', text: 'Aphthous ulcers (recurrent aphthous stomatitis) are characterized by:', options: ['Painful, round/oval ulcers with yellow-gray pseudomembrane and red halo on non-keratinized mucosa', 'Grouped vesicles on keratinized mucosa', 'White patches', 'Bone lesions'], correct: 0, exp: 'Minor aphthae are <1 cm, round/oval, on movable non-keratinized mucosa; heal in 7–14 days without scarring.' },
    { specialty: 'Oral Medicine & Pathology', text: 'Mucocele most commonly occurs on:', options: ['Lower lip (mucus extravasation cyst)', 'Upper lip', 'Hard palate', 'Gingiva'], correct: 0, exp: 'Mucocele is caused by ruptured minor salivary gland duct with mucus extravasation into surrounding tissue; 75% occur on the lower lip.' },
    { specialty: 'Oral Medicine & Pathology', text: 'Ranula is a mucocele of which gland?', options: ['Sublingual gland or submandibular gland duct (Wharton\'s duct)', 'Parotid gland', 'Accessory salivary gland', 'Von Ebner\'s gland'], correct: 0, exp: 'Ranula is a large mucocele in the floor of mouth, arising from the sublingual or submandibular gland ductal obstruction.' },
    { specialty: 'Oral Medicine & Pathology', text: 'Oral candidiasis most commonly presents as:', options: ['Pseudomembranous type (thrush) — white plaques that can be wiped off', 'Erythroplakia', 'Ulceration', 'Blue-black pigmentation'], correct: 0, exp: 'Pseudomembranous candidiasis ("thrush") shows white curdy plaques that wipe off to reveal an erythematous base.' },
    { specialty: 'Oral Medicine & Pathology', text: 'Herpes labialis (cold sores) is caused by:', options: ['HSV-1 (Herpes Simplex Virus type 1)', 'HSV-2', 'Varicella-zoster', 'EBV'], correct: 0, exp: 'HSV-1 causes recurrent herpes labialis (cold sores at the vermillion border); primary infection presents as herpetic gingivostomatitis in children.' },
    { specialty: 'Oral Medicine & Pathology', text: 'Sjögren\'s syndrome is characterized by:', options: ['Dry eyes (xerophthalmia), dry mouth (xerostomia), and positive anti-Ro/La antibodies', 'Wet mouth and dry eyes only', 'Only salivary gland enlargement', 'High salivary flow'], correct: 0, exp: 'Primary Sjögren\'s: keratoconjunctivitis sicca + xerostomia. Secondary: associated with rheumatoid arthritis or other autoimmune diseases.' },
    { specialty: 'Oral Medicine & Pathology', text: 'Oral lichen planus most commonly presents as:', options: ['Bilateral reticular (Wickham\'s striae) on buccal mucosa', 'Unilateral plaque on tongue', 'Ulcers only', 'Pigmentation'], correct: 0, exp: 'Reticular OLP shows bilateral interlacing white lines (Wickham\'s striae) on the buccal mucosa; erosive type is painful.' },
    { specialty: 'Oral Medicine & Pathology', text: 'Torus palatinus is:', options: ['Benign bony exostosis on the midline of hard palate', 'A cyst', 'A neoplasm', 'A mucocele'], correct: 0, exp: 'Torus palatinus is a common developmental bony outgrowth on the midline palate; treatment only if it interferes with a prosthesis.' },
    { specialty: 'Oral Medicine & Pathology', text: 'The most reliable diagnostic tool for oral cancer is:', options: ['Incisional biopsy + histopathology', 'X-ray', 'Clinical examination only', 'Toluidine blue staining alone'], correct: 0, exp: 'Histopathological examination of biopsy tissue is the gold standard for diagnosing and staging oral cancer.' },
    { specialty: 'Oral Medicine & Pathology', text: 'Burning mouth syndrome (BMS) is most common in:', options: ['Post-menopausal women', 'Children', 'Young men', 'Pregnant women'], correct: 0, exp: 'BMS affects primarily post-menopausal women; it presents as burning sensation without visible lesions and may relate to hormonal changes.' },

    // ─── DENTAL ETHICS (~20) ──────────────────────────────────────────────────
    { specialty: 'Dental Ethics', text: 'Which bioethical principle requires a dentist to always act in the patient\'s best interest?', options: ['Beneficence', 'Autonomy', 'Justice', 'Veracity'], correct: 0, exp: 'Beneficence is the duty to act in the patient\'s best interest; it includes both treating disease and promoting well-being.' },
    { specialty: 'Dental Ethics', text: 'Informed consent must include:', options: ['Diagnosis, treatment options, risks, benefits, and alternatives', 'Patient signature only', 'Dental fee only', 'Radiograph results'], correct: 0, exp: 'Informed consent requires explanation of the diagnosis, proposed treatment, alternatives, risks, benefits, and the right to refuse.' },
    { specialty: 'Dental Ethics', text: 'Patient confidentiality may be breached when:', options: ['There is a risk of serious harm to third parties or public health reporting requirements', 'The receptionist asks', 'The patient owes money', 'Another dentist requests records'], correct: 0, exp: 'Confidentiality can be overridden in cases of mandatory reporting (child abuse, communicable diseases) or imminent harm to identifiable third parties.' },
    { specialty: 'Dental Ethics', text: 'Nonmaleficence in dental ethics means:', options: ['Do not harm the patient', 'Treat the patient', 'Be fair to all patients', 'Tell the truth'], correct: 0, exp: 'Nonmaleficence ("first, do no harm") obliges dentists to avoid treatments whose risks outweigh benefits.' },
    { specialty: 'Dental Ethics', text: 'A patient refuses a radiograph that the dentist considers necessary. The dentist should:', options: ['Respect patient\'s autonomy, document the refusal, and explain risks of proceeding without X-ray', 'Proceed regardless', 'Dismiss the patient immediately', 'Take X-ray without consent'], correct: 0, exp: 'Patient autonomy is paramount; the dentist must respect refusal, document it, and advise of consequences before proceeding.' },
    { specialty: 'Dental Ethics', text: 'What is the ethical basis for providing emergency care even without full payment?', options: ['Beneficence and duty of care', 'Legal liability only', 'Personal financial gain', 'Marketing strategy'], correct: 0, exp: 'Emergency dental care is an ethical obligation rooted in beneficence and the duty of care owed to patients in pain.' },
    { specialty: 'Dental Ethics', text: 'Double effect principle in dental ethics applies when:', options: ['A treatment (e.g., pain medication) has both good and harmful effects, and the intention is good', 'A treatment is only harmful', 'Emergency extraction is refused', 'Payment is disputed'], correct: 0, exp: 'The principle of double effect permits a treatment with harmful side effects if the intent is to achieve a proportionate good (e.g., opioids for terminal pain).' },
    { specialty: 'Dental Ethics', text: 'The legal doctrine that requires dentists to disclose information a "reasonable patient" would want to know is called:', options: ['The reasonable patient standard (patient-oriented standard)', 'Res ipsa loquitur', 'Respondeat superior', 'Duty of referral'], correct: 0, exp: 'The patient-oriented standard requires disclosure of what a reasonable patient in that situation would want to know — broader than the professional standard.' },
    { specialty: 'Dental Ethics', text: 'Which describes a conflict of interest for a dentist?', options: ['Recommending a treatment from which the dentist profits without disclosing the financial relationship', 'Referring to a specialist', 'Treating a family member', 'Working in multiple clinics'], correct: 0, exp: 'A conflict of interest exists when financial or personal interest potentially conflicts with professional duties; it requires disclosure.' },
    { specialty: 'Dental Ethics', text: 'Justice in bioethics for dental practice means:', options: ['Fair distribution of healthcare resources and treating patients equitably', 'Winning legal cases', 'Only treating insured patients', 'Charging equal fees'], correct: 0, exp: 'Justice requires equitable treatment of all patients, fair allocation of resources, and non-discriminatory care regardless of background.' },
    { specialty: 'Dental Ethics', text: 'A dentist notices signs of domestic abuse in an adult patient. The ethical approach is:', options: ['Create a safe environment, document observations, and follow mandatory reporting laws', 'Immediately call police without informing patient', 'Do nothing', 'Ask the partner present in the room'], correct: 0, exp: 'Dentists should ensure patient safety, document findings carefully, and comply with local mandatory reporting obligations for suspected abuse.' },
];

const seed300 = async () => {
    try {
        await sequelize.authenticate();
        console.log('✅ DB Connected');

        const specialties = await Specialty.findAll();
        if (!specialties.length) {
            console.error('❌ No specialties found. Seed specialties first.');
            process.exit(1);
        }

        const specMap = new Map(specialties.map(s => [s.name, s.id]));

        let created = 0;
        for (const q of questions) {
            const specId = specMap.get(q.specialty);
            if (!specId) {
                console.warn(`⚠️  Specialty not found: ${q.specialty}`);
                continue;
            }

            const existing = await Question.findOne({ where: { text: q.text } });
            if (existing) continue; // Skip duplicates

            const difficulty = created % 3 === 0 ? 'hard' : created % 3 === 1 ? 'medium' : 'easy';
            const createdQ = await Question.create({
                text: q.text,
                specialtyId: specId,
                difficulty,
                isActive: true
            });

            for (let i = 0; i < q.options.length; i++) {
                await Option.create({
                    questionId: createdQ.id,
                    text: q.options[i],
                    isCorrect: i === q.correct,
                    order: String.fromCharCode(65 + i)
                });
            }

            await Explanation.create({
                questionId: createdQ.id,
                text: q.exp
            });

            created++;
        }

        console.log(`\n✅ ${created} questions added to the database!`);
        const total = await Question.count();
        console.log(`📊 Total questions now in DB: ${total}`);
        process.exit(0);
    } catch (err) {
        console.error('❌ Error:', err.message);
        process.exit(1);
    }
};

seed300();
