// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsoLuEniuo6nJRoq_t6aQtvgRn_KVsHsA',
    appId: '1:175761970134:web:1931e6e427e299f7f04a77',
    messagingSenderId: '175761970134',
    projectId: 'medicalq',
    authDomain: 'medicalq.firebaseapp.com',
    storageBucket: 'medicalq.firebasestorage.app',
    measurementId: 'G-LHJMEH9H84',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtDlMSJDtmeka4pntO6BEFT7NEEdLCUro',
    appId: '1:175761970134:android:674157f854739134f04a77',
    messagingSenderId: '175761970134',
    projectId: 'medicalq',
    storageBucket: 'medicalq.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh8wTBcxTvDZ57iAGaWc5Ee6yQnzEBTfs',
    appId: '1:175761970134:ios:f05c6adb8b160843f04a77',
    messagingSenderId: '175761970134',
    projectId: 'medicalq',
    storageBucket: 'medicalq.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh8wTBcxTvDZ57iAGaWc5Ee6yQnzEBTfs',
    appId: '1:175761970134:ios:f05c6adb8b160843f04a77',
    messagingSenderId: '175761970134',
    projectId: 'medicalq',
    storageBucket: 'medicalq.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsoLuEniuo6nJRoq_t6aQtvgRn_KVsHsA',
    appId: '1:175761970134:web:6acc2b0722fd194ff04a77',
    messagingSenderId: '175761970134',
    projectId: 'medicalq',
    authDomain: 'medicalq.firebaseapp.com',
    storageBucket: 'medicalq.firebasestorage.app',
    measurementId: 'G-ECJSTF21J7',
  );
}
