name: Build Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-apk:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get dependencies
        working-directory: frontend
        run: flutter pub get

      - name: Build APK
        working-directory: frontend
        run: flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: medical-q-app-release
          path: frontend/build/app/outputs/flutter-apk/app-release.apk
